# -*- coding: utf-8 -*-
"""normalequation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mNM2JOIk5BAeoHpejaOfsrGZAEgSGpVh
"""

from sklearn.datasets import make_regression
x_data,y_data=make_regression(n_samples=500, n_features=15,random_state=10)

# Write the formula of Normal equation

import numpy as np
x_b=np.c_[np.ones((500,1)),x_data] # add vector of ones to x_data 
inverseX=np.linalg.inv(np.dot(x_b.T,x_b))
XY=np.dot(x_b.T,y_data)
theta=np.dot(inverseX,XY)
print("thetas: " ,theta)